Skip Echo conversion test when extension is not loaded
Without Echo ConversionStrategyTest::testGetPostprocessor() fails cause
it requires MediaWiki\Extension\Notifications\AttributeManager:

Error: Class "MediaWiki\Extension\Notifications\AttributeManager" not found

Notifications.php:68
includes/Import/Postprocessor/LqtNotifications.php:53
includes/Import/Postprocessor/LqtNotifications.php:41
includes/Import/LiquidThreadsApi/ConversionStrategy.php:141
tests/phpunit/integration/Import/LiquidThreadsApi/ConversionStrategyTest.php:163

The test exercises the system that converts LiquidThreads notifications
to Echo notifications and thus requires Echo to be loaded.

Skip the test when Echo is not loaded. The test will be run on CI since
Echo is added as a dependency to Flow.

Bug: T389998
Change-Id: Ia1423a2f1be9223d6597f60e7bd99fa022ee165a