Update patch set 1
Patch Set 1: Code-Review-1

I cherry-picked this on top of master, and in Special:ApiSandbox when I choose action=flow and prop=flow I get an endless spinner, the buttons don't enable, and the JS error:

TypeError: this.params is undefined
http://localhost/wiki/extensions/ApiSandbox/resources/UiBuilder.js
Line 62

(I'll file a bug that Extension:ApiSandbox should be more bulletproof.)

It seems ApiQueryPropFlow does not return a parameters array in its response to api.php?querymodules=flow&format=json&action=paraminfo.  Is the failure because this is dependent on another patch?

Patch-set: 1