Update patch set 14
Patch Set 14: Code-Review-1

I added new topic and new post, clicked Preview, got

Error: Syntax error, unrecognized expression: < form textarea

from Sizzle.error

apiRequest() is doing 
$target = flowBoard.$container.find( dataParams.flowApiTarget );
which is probably from flow_preview_button.handlebars

Patch-set: 14
Label: Code-Review=-1