Change DROP KEY TO DROP INDEX
According to https://github.com/wikimedia/mediawiki-extensions-Flow/commit/5bf7057a1a01967aa05f6296cf850587ffedb419
it doesn't mention anything about dropping a key. Also i can't find the
key in flow.sql which is last updated in 2015.

It will most likly fix beta's problem
nError: 1091 Can't DROP 'flow_ext_ref_idx_v2'; check that column/key exists
(10.68.23.30)\n\nBacktrace:\n#0 /srv/mediawiki-staging/php-master/includes/libs/rdbms/database/Database.php(967):
Wikimedia\\Rdbms\\Database->reportQueryError(string, integer, string, string, boolean)\n#1 /srv/mediawiki-staging/php-

Change-Id: I0723a21e4e275e840c04788e0f9d2e45a65f2d45