Update patch set 2
Patch Set 2:

This causes a new problem for me:
A database query error has occurred.
Query: DROP INDEX IF EXISTS flow_wiki_ref_idx ON `bw_flow_wiki_ref`

Error: 1064 You have an error in your SQL syntax

Patch-set: 2
Reviewer: Nikerabbit <93@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0