Update patch set 1
Patch Set 1: Code-Review-1

This fails with

    Exception thrown by ext.flow.parsoid: mw.flow is undefined
    load.p...060653Z (line 151)
    TypeError: mw.flow is undefined

    ...itor.init);}(jQuery,mediaWiki));;},{},{});mw.loader.implement("ext.flow.parsoid"...

ext.flow.parsoid correctly depends on ext.base.js which initializes mw.flow.  BUT the latter does it in a jQuery document ready shortcut function, while ext.flow.parsoid adds to mw.flow immediately upon load. Fix coming.

Patch-set: 1
Label: Code-Review=-1