Use container namespace
Fatal error: Class 'Container' not found in extensions/Flow/FlowActions.php on line 102

Change-Id: I00d32ecec87ac198a265180c0485d84ff1579101
(cherry picked from commit 1aadc54bca4dd79610e918c1e243ab26b4a19ef2)