Update patch set 6
Patch Set 6:

When I test the full wiki import, I get a duplicate key error:

vagrant@mediawiki-vagrant:~$ mwscript extensions/Flow/maintenance/importDump.php --wiki=wiki /vagrant/full_Flow_wiki_dump_all_history_abef2046e70b4440d11078f238e3cf9eb03bdfb8.xml
A database query error has occurred.
Query: INSERT  INTO `flow_workflow` (workflow_id,workflow_type,workflow_wiki,workflow_page_id,workflow_namespace,workflow_title_text,workflow_lock_state,workflow_last_update_timestamp,workflow_name) VALUES ('4GE�����B','topic','wiki','112','3','New_board_2015-05-01','0','20150501233052','')
Function: Flow\Data\Storage\BasicDbStorage::insert (flow_workflow)
Error: 1062 Duplicate entry '\x054GE\xFF\xD2\x1F\xE9\x93\xE2B' for key 'PRIMARY' (127.0.0.1)

Backtrace:
#0 /vagrant/mediawiki/includes/db/Database.php(1047): DatabaseBase->reportQueryError('Duplicate entry...', 1062, 'INSERT  INTO `f...', 'Flow\Data\Stora...', false)
#1 /vagrant/mediawiki/includes/db/Database.php(1935): DatabaseBase->query('INSERT  INTO `f...', 'Flow\Data\Stora...')
#2 /vagrant/mediawiki/extensions/Flow/includes/Data/Storage/BasicDbStorage.php(68): DatabaseBase->insert('flow_workflow', Array, 'Flow\Data\Stora...')
#3 /vagrant/mediawiki/extensions/Flow/includes/Data/ObjectManager.php(245): Flow\Data\Storage\BasicDbStorage->insert(Array)
#4 /vagrant/mediawiki/extensions/Flow/includes/Data/ObjectManager.php(170): Flow\Data\ObjectManager->insert(Array, Array)
#5 /vagrant/mediawiki/extensions/Flow/includes/Data/ObjectManager.php(143): Flow\Data\ObjectManager->multiPut(Array, Array)
#6 /vagrant/mediawiki/extensions/Flow/includes/Data/ManagerGroup.php(80): Flow\Data\ObjectManager->put(Object(Flow\Model\Workflow), Array)
#7 /vagrant/mediawiki/extensions/Flow/includes/Dump/Importer.php(121): Flow\Data\ManagerGroup->put(Object(Flow\Model\Workflow), Array)
#8 /vagrant/mediawiki/extensions/Flow/includes/Dump/Importer.php(188): Flow\Dump\Importer->put(Object(Flow\Model\Workflow))
#9 /vagrant/mediawiki/extensions/Flow/includes/Dump/Importer.php(75): Flow\Dump\Importer->handleTopic()
#10 /vagrant/mediawiki/extensions/Flow/maintenance/importDump.php(97): Flow\Dump\Importer->doImport()
#11 /vagrant/mediawiki/extensions/Flow/maintenance/importDump.php(73): FlowBackupReader->importFromHandle(Resource id #313)
#12 /vagrant/mediawiki/extensions/Flow/maintenance/importDump.php(54): FlowBackupReader->importFromFile('/vagrant/full_F...')
#13 /vagrant/mediawiki/maintenance/doMaintenance.php(103): FlowBackupReader->execute()
#14 /vagrant/mediawiki/extensions/Flow/maintenance/importDump.php(102): require_once('/vagrant/mediaw...')
#15 /var/www/w/MWScript.php(89): require_once('/vagrant/mediaw...')
#16 {main}

This shouldn't even be generating UIDs, so it's similar to T117907 but different.

Patch-set: 6