Update patch set 1
Patch Set 1:

Well one template sort of works.  Trying mw.mantle.template.get( 'foo').render() for each template I added to ext.flow.new, I found:

'flow_board_navigation.html.handlebars' -> renders something if I supply options.hash. Yay!

flow_topic.html.handlebars -> Missing helper: 'uuidTimestamp' (modules/new/flow-handlebars.js has a timestamp helper, but not uuidTimestamp.

flow_reply_form.html.handlebars -> 
Error: Parse error on line 6: ...#if @root.submitted && @root.submitted.p -----------------------^ Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'NUMBER', 'BOOLEAN', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'DATA', 'SEP', got 'INVALID'

flow_topic_navigation.html.handlebar -> Error: Parse error on line 19: ... ( links.pagination && links.pagination.

flow_newtopic_form.html.handlebars -> (whitespace)

flow_block_topiclist.html.handlebars -> Error: The partial flow_board_navigation could not be found [even though 'flow_board_navigation.html.handlebars' works].

Patch-set: 1
Label: Verified=0