Update patch set 2
Patch Set 2: Code-Review-1

(1 comment)

Also getting:

Exception thrown by ext.flow.editors.none
TypeError: invalid 'instanceof' operand originFn

Haven't yet figured out what exactly iss causing that, but prior to this patch I wasn't seeing this.

Patch-set: 2
Label: Code-Review=-1