Update patch set 11
Patch Set 11: Code-Review-1

Looks good for the most part. Using inline blocks for the definitions makes for some long lines, but that may be unavoidable anyhow and it's easy enough to read.

The collapse feature is now failing, however, on account of a missing `topic_hide_button`.

  /Users/.../browser $ bundle exec cucumber features/collapse.feature:4
  @chrome @clean @ee-prototype.wmflabs.org @en.wikipedia.beta.wmflabs.org @firefox @internet_explorer_10 @login @test2.wikipedia.org
  Feature: Topic collapsing
  
    Background:                                                               # features/collapse.feature:4
      Given I am logged in                                                    # mediawiki_selenium-0.4.0/lib/mediawiki_selenium/step_definitions/login_steps.rb:12
      And I am on Flow page                                                   # features/step_definitions/flow_steps.rb:5
      And I have created a Flow topic with title "Non-Moderated Topic"        # features/step_definitions/flow_steps.rb:16
      And I have created a Flow topic with title "Hidden Topic"               # features/step_definitions/flow_steps.rb:16
      And I click the Topic Actions link                                      # features/step_definitions/flow_steps.rb:75
      And I click the Hide topic button                                       # features/step_definitions/flow_steps.rb:63
        undefined method `topic_hide_button_element' for #<FlowPage:0x0000010464f5a0> (NoMethodError)
        ./features/step_definitions/flow_steps.rb:64:in `/^I click the Hide topic button$/'
        features/collapse.feature:12:in `And I click the Hide topic button'

Patch-set: 11
Reviewer: Dduvall <1731@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Code-Review=-1