Update patch set 4
Patch Set 4: Code-Review-1

(2 comments)

Even with Mantle change Iaaf01b521be91b53 ("Register all handlebars templates as partials as well"), when I click to sort by <Recent active topics> my local wiki dies in flow-handlebars.js's FlowHandlebars.prototype.eachPost() 
  line 443    var revId = context.posts[postIds][0],
TypeError: context is undefined
Also the todo in there to handle an array of postIds seems a must-fix, that would also crash the JS.

General patch complaint/suggestions:
* You need to rebase this patch on latest frontend-rewrite, which has JS/RL message fixes and a lot of template improvements.
* It would be better to make renaming all the file.html.handlebars a separate patch so this isn't cluttered with mechanical changes. I.e. the commit stack is api-interation on rename_templates on latest frontend-rewrite.
* Don't wrap quick fixes into substantial code changes. The unrelated fixes to flow_block_topic_reply.handlebars and flow_block_header.handlebars should have been separate quick fixes to tip of frontend-rewrite that are easy to review.
* The commit message should mention the required Mantle change.
* Commit message should say what it does ("add UI.events.apiHandlers and UI.events.interactiveHandlers.apiRequest"?, and which api handlers have been implemented (I think just filter sorting in flow_board_navigation.handlebars). Ten minutes spent crafting a better commit message encourages review and saves precious reviewers' time.

Patch-set: 4
Label: Code-Review=-1