Update patch set 16
Patch Set 16: Code-Review-1

Got a strange error when running the maintenance script:
Query: UPDATE  `flow_workflow` SET workflow_namespace = '2600',workflow_title_text = 'Rxbz5wmataih52ed',workflow_user_text = NULL WHERE workflow_id = 'Tg\r6���e'
Function: Flow\Data\BasicDbStorage::update (flow_workflow)
Error: 1054 Unknown column 'workflow_user_text' in 'field list' (localhost)

Purging memcached clears the problem, this is probably related to obsolete data in the cache.  Not sure why this happens yet since workflow_user_text was dropped long time ago and the cache is pretty new.

Another issue is that since the workflow is now pointing to a topic title, the link for "This topic starts on XXX board" is not linking to the board.

Patch-set: 16
Label: Code-Review=-1