Don't assume ve exists
We properly check isSupported before actually using any ve code,
but we blindly pass variable 've' even though it may not exist,
causing a:
    ReferenceError: ve is not defined
This is not actually breaking anything, just some console noise.

Change-Id: Ie04298960cad187d920e230c2c91f691936b405d