Don't assume mw.flow.editor already exists
Editors JS is only loaded when editors are initialized.

We have some code to compress textareas for all "hidden forms",
which will go through this altered code on pageload. At that
point, editors JS hasn't yet been loaded (it doesn't really
make sense to make it call compessTextareas at that point, but
code re-use, I guess)

Anyway, let's just be safe and don't attempt to destroy them
if they've never even been initialized.
Then we'll no longer see errors like:
TypeError: mw.flow.editor is undefined

Change-Id: I8812bb2381077a71d642e414747e683466509076