header editing is broken for headers created by anon users
Fatal error: Call to a member function getName() on a non-object
in /Flow/includes/Block/Topic.php on line 533

This is mainly because User::newFromName() would fail on IPs by default

Change-Id: I8df80b0a959cd7acfafa091ca89d98ad6cf952af